name: Deploy to Google Compute Engine

on:
  push:
    branches:
      - main 
env:
    SERVIE_NAME: ${{ github.event.repository.name }} 
    PROJECT_ID: ${{ secrets.PROJECT_ID }}
    INSTANCE: ${{ secrets.INSTANCE }}
    ENV_FILE: env/main.env
    HOST: localhost
    DOMAIN: eventos

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: test-senior-developer
        install_components: 'compute'  
    - name: List Compute Engine Instances
      run: |
        gcloud compute instances list --project test-senior-developer
    - name: Deploy 
      run: |
        gcloud compute scp --recurse /home/runner/work/$SERVIE_NAME/$SERVIE_NAME yohan_gomez@$INSTANCE:/home/yohan_gomez --zone=us-central1-a
    - name: Verificar archivos en la instancia de GCE
      run: |
          gcloud compute ssh yohan_gomez@$INSTANCE --zone=us-central1-a --command="ls -la /home/yohan_gomez/$SERVIE_NAME && cat /home/yohan_gomez/$SERVIE_NAME/deploy.sh"
    - name: Env variable
      run: |
        echo "GCP_PROJECT=${{env.PROJECT_ID}}" >> ${{ env.ENV_FILE }}
        echo "SERVICE_NAME=${{env.SERVICE_NAME}}" >> ${{ env.ENV_FILE }}
        echo "HOST=${{env.HOST}}" >> ${{ env.ENV_FILE }}
        echo "DOMAIN=${{env.DOMAIN}}" >> ${{ env.ENV_FILE }}
        echo "USER_DB=${{ secrets.POSTGRES_USER }}" >> ${{ env.ENV_FILE }}
        echo "PASSWORD_DB=${{ secrets.POSTGRES_PASSWORD }}" >> ${{ env.ENV_FILE }}
        echo "DB_NAME=${{ secrets.DB_NAME }}" >> ${{ env.ENV_FILE }}
        echo "PORT_DB=${{ secrets.POSTGRES_PORT }}" >> ${{ env.ENV_FILE }}
        echo "REDIS_HOST=${{ secrets.REDIS_HOST }}" >> ${{ env.ENV_FILE }} 
        echo "REDIS_PORT=${{ secrets.REDIS_PORT }}" >> ${{ env.ENV_FILE }}
    - name: Create ENV File
      run: touch .env && cp ${{ env.ENV_FILE }} .env
    - name: Ejecutar depliegue
      run: |
          gcloud compute ssh yohan_gomez@$INSTANCE --zone=us-central1-a --command="cd /home/yohan_gomez/$SERVIE_NAME/ && chmod +x deploy.sh && POSTGRES_PASSWORD=$POSTGRES_PASSWORD ./deploy.sh"